package KieRule

import com.github.romankh3.droolsspringboot.Order;
import com.github.romankh3.droolsspringboot.OutputDisplay;

global OutputDisplay showResults;

rule "MASTERCARD"
    when
        orderObject : Order(cardType == "MASTERCARD" && price > 10000);
    then
        orderObject.setDiscount(10);
        showResults.showText("MASTERCARD has been added a discount");
end;

rule "VISA"
    when
        orderObject : Order(cardType == "VISA" && price > 5000);
    then
        orderObject.setDiscount(14);
        showResults.showText("VISA has been added a discount");
end;

rule "ICICI"
    when
        orderObject : Order(cardType == "ICICI" && price > 3000);
    then
        orderObject.setDiscount(20);
        showResults.showText("ICICI has been added a discount");
end;
